# Generated by Django 4.0.4 on 2022-04-27 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 18, 7, 39, 191827, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
