# Generated by Django 4.0.4 on 2022-05-04 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comment_c_time_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 14, 52, 47, 330804, tzinfo=utc), verbose_name='date published'),
        ),
    ]
