# Generated by Django 4.0.4 on 2022-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_image_alter_comment_c_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
