# Generated by Django 4.0.4 on 2022-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_image_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
